Case #1: FFT 3/1
Case #2: FFT 2/1
Case #3: TTFFFT 4/1
Case #4: FF 1/1
Case #5: TTTF 3/1
Case #6: TTFTTTFTTTFFFFFFFTFTTTTTTFFFTFTTTFTFTTFFTFTTFTTFFFTFTFTTFTFTFFTTTTFTFTTTTFFFTFFTFFFFTTTFFTTTTTFFTTFTTFTTFFFTTTTFFTTFTFFT 65/1
Case #7: TTTTTTTTTT 10/1
Case #8: TTTTTTTTTF 9/1
